/**
 * First-run bootstrap wizard (Stage 1 — Enhancement #17).
 *
 * Interactive `smartnote --setup` flow:
 *   1. Ensures the data directory exists (SQLite schema bootstrapped on first run).
 *   2. Optionally configures AI features (LLM key) and email notifications (SMTP),
 *      or stays fully offline.
 *   3. Writes/updates `<data-dir>/.env` (0600) which the launcher loads via dotenv.
 *
 * Non-interactive mode: set SMARTNOTE_SETUP_NONINTERACTIVE=1 to only ensure the
 * data dir + .env skeleton exists (used by launchers / CI smoke tests).
 */
import fs from "node:fs";
import path from "node:path";
import readline from "node:readline/promises";
import { getDataDir, getSqliteDbPath, isPortableMode } from "./paths";
import { SQLITE_DDL } from "../db";
import { createLogger } from "./logging";

const log = createLogger("setup");

function ask(rl: readline.Interface, question: string): Promise<string> {
  return rl.question(question);
}

/** Read existing .env lines so we can update keys without losing custom settings. */
function readEnvFile(envPath: string): Map<string, string> {
  const map = new Map<string, string>();
  if (!fs.existsSync(envPath)) return map;
  for (const line of fs.readFileSync(envPath, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (m && !line.trim().startsWith("#")) map.set(m[1], m[2]);
  }
  return map;
}

function writeEnvFile(envPath: string, values: Map<string, string>): void {
  const lines = [
    "# SmartNote Scheduler — portable configuration",
    "# Generated by `smartnote --setup`. Edit freely; restart to apply.",
    "",
    ...Array.from(values.entries()).map(([k, v]) => `${k}=${v}`),
    "",
  ];
  fs.writeFileSync(envPath, lines.join("\n"), { mode: 0o600 });
}

/** Ensure SQLite storage is initialized (idempotent). */
async function ensureDatabase(): Promise<string> {
  const dbFile = getSqliteDbPath();
  fs.mkdirSync(path.dirname(dbFile), { recursive: true });
  const mod = await import("better-sqlite3");
  const Database = (mod.default ?? mod) as typeof import("better-sqlite3");
  const client = new Database(dbFile);
  try {
    client.pragma("journal_mode = WAL");
    client.pragma("foreign_keys = ON");
    client.exec(SQLITE_DDL);
  } finally {
    client.close();
  }
  return dbFile;
}

export async function runSetupWizard(): Promise<void> {
  // Auto-fallback to non-interactive when stdin is not a TTY (piped input, CI,
  // launchers) so the wizard never hangs waiting for answers it can't get.
  const nonInteractive =
    process.env.SMARTNOTE_SETUP_NONINTERACTIVE === "1" || !process.stdin.isTTY;
  const dataDir = getDataDir();
  console.log(`\n  SmartNote Scheduler — first-run setup`);
  console.log(`  Data directory: ${dataDir}\n`);

  const dbFile = await ensureDatabase();
  console.log(`  ✔ Storage ready (SQLite): ${dbFile}`);

  const envPath = path.join(dataDir, ".env");
  const values = readEnvFile(envPath);
  values.set("DB_DRIVER", "sqlite");

  if (nonInteractive) {
    writeEnvFile(envPath, values);
    console.log(`  ✔ Config written: ${envPath} (non-interactive)\n`);
    return;
  }

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  try {
    console.log("  Optional integrations — press Enter to skip any of these and stay fully offline.\n");

    const llmKey = (await ask(rl, "  [1/3] AI features — enter LLM API key (or Enter to skip): ")).trim();
    if (llmKey) {
      values.set("BUILT_IN_FORGE_API_KEY", llmKey);
      const baseUrl = (await ask(rl, "        LLM base URL (Enter for default): ")).trim();
      if (baseUrl) values.set("BUILT_IN_FORGE_API_URL", baseUrl);
      console.log("        ✔ AI categorization & smart reminders will be enabled.");
    } else {
      values.delete("BUILT_IN_FORGE_API_KEY");
      console.log("        Offline mode: rule-based categorization only.");
    }

    const webhookUrl = (await ask(rl, "  [2/3] Email reminders — email webhook URL (or Enter to skip): ")).trim();
    if (webhookUrl) {
      values.set("EMAIL_WEBHOOK_URL", webhookUrl);
      const webhookKey = (await ask(rl, "        Webhook API key (Enter for none): ")).trim();
      if (webhookKey) values.set("EMAIL_WEBHOOK_API_KEY", webhookKey);
      console.log("        ✔ Reminder emails will be sent via the webhook.");
    } else {
      for (const k of ["EMAIL_WEBHOOK_URL", "EMAIL_WEBHOOK_API_KEY"]) values.delete(k);
      console.log("        In-app reminders only (browser must be open while app runs).");
    }

    const portRaw = (await ask(rl, "  [3/3] Port to serve on [3000]: ")).trim();
    const portNum = Number.parseInt(portRaw || "3000", 10);
    if (Number.isFinite(portNum) && portNum > 0 && portNum < 65536) {
      values.set("PORT", String(portNum));
    }
  } finally {
    rl.close();
  }

  writeEnvFile(envPath, values);
  console.log(`\n  ✔ Configuration saved: ${envPath}`);
  console.log(`  Start the app with: smartnote${isPortableMode() ? "" : " (dev: pnpm dev)"}`);
  console.log(`  Your notes live in: ${dataDir} — copy that folder to move everything.\n`);
  log.info("Setup wizard completed", { envPath });
}
